# see docs:
# https://github.com/greshake/i3status-rust/blob/master/blocks.md
[theme]
theme = "solarized-dark"
[icons]
icons = "awesome6"

[[block]]
block = "focused_window"
[block.theme_overrides]
idle_bg = "#795def"
idle_fg = "#2b2a33"

[[block]]
block = "external_ip"
format = " $ip "

[[block]]
block = "custom"
command = "echo [$(cat /mnt/16m/pwd.txt)]"
interval = 30

[[block]]
block = "disk_space"
path = "/"
format = "$icon $available"
info_type = "available"
###alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:1) "
interval = 30
warning_mem = 70
critical_mem = 90


[[block]]
block = "cpu"
format = "$icon $barchart $utilization"
interval = 5

[[block]]
block = "load"
interval = 5

#[[block]]
#block = "custom"
#command = "amixer -c 1 sget Master"
##command = "amixer -c 1 sget Master | awk -F\"[][]\" '/db/ { print $2}'"
#interval = 100
##command = "echo hey wassap"

#[[block]]
#block = "sound"
#[[block]]
#block = "weather"
#format = "{weather} ({location}) {temp}°, {wind} m/s {direction}"
#service = { name = "openweathermap", api_key = "b505355dd47a36c41be813889b83c2cd", city_id = "5398563", units = "metric" }
[[block]]
block = "custom"
cycle = ["echo SND"]
#on_click = "pavucontrol"

#[[block]]
#block = "custom"
#cycle = ["echo kbd: EN", "echo kbd: RU"]
#on_click = "pavucontrol"

[[block]]
block = "custom"
cycle = ["echo ⚙️"]
#on_click = "exec env XDG_CURRENT_DESKTOP=GNOME gnome-control-center"

[[block]]
block = "battery"
format = " $icon $percentage "
good = 60
warning = 40
critical = 20

# [[block]]
# block = "custom"
# command = "echo BAT: $(cat /sys/class/power_supply/BAT0/capacity)%"
# interval = 100

[[block]]
block = "time"
interval = 60

[[block]]
block = "net"
#format = " $ip "
