# see docs:
# https://github.com/greshake/i3status-rust/blob/master/blocks.md
theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "net"
device = "enp10s0"
ssid = true
ip = true
speed_up = true 
graph_up = true
interval = 5

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

#[[block]]
#block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
