# see docs:
# https://github.com/greshake/i3status-rust/blob/master/blocks.md
theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "custom"
command = "echo 📁 [$(cat /mnt/16m/pwd.txt)]"
interval = 1

#need to figure out network name
#[[block]]
#block = "net"
#device = "enp10s0"
#ssid = true
#ip = true
#speed_up = false
#graph_up = false 
#interval = 5
#
[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

#[[block]]
#block = "custom"
#command = "amixer -c 1 sget Master"
##command = "amixer -c 1 sget Master | awk -F\"[][]\" '/db/ { print $2}'"
#interval = 100
##command = "echo hey wassap"

#[[block]]
#block = "sound"
#[[block]]
#block = "weather"
#format = "{weather} ({location}) {temp}°, {wind} m/s {direction}"
#service = { name = "openweathermap", api_key = "b505355dd47a36c41be813889b83c2cd", city_id = "5398563", units = "metric" }
[[block]]
block = "custom"
cycle = ["echo SND"]
on_click = "pavucontrol"

[[block]]
block = "custom"
cycle = ["echo ⚙️"]
on_click = "exec env XDG_CURRENT_DESKTOP=GNOME gnome-control-center"

[[block]]
block = "custom"
command = "echo BAT: $(cat /sys/class/power_supply/BAT0/capacity)%"
interval = 100

#format = "{weather} ({location}) {temp}°, {wind} m/s {direction}"
#service = { name = "openweathermap", api_key = "b505355dd47a36c41be813889b83c2cd", city_id = "5398563", units = "metric" }


[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
